name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to ECS
      run: |
        ssh -o StrictHostKeyChecking=no ec-user@3.27.121.14 << 'EOF'
          cd /var/www/html/uts-cloud-computing
          sudo git pull origin main
          sudo systemctl restart httpd
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
